### ISSUE TITLE
normal weather map?

### ISSUE THREAD

**Issue by frensher** [Cihsaing/SJDL-Foggy-Vehicle-Re-Identification--AAAI2022#2]
cool job! 
your id can solve the fog weather problem.
i want ask did you make exprimrnt in real normal weather?
your id staill make work in normal weather

**Comment by Cihsaing** [comment]
Thank you!

Due to the data source limitation, we can only maximum the percent of real hazy data, and there are some normal image in the gallery data as inference source..

In private, we also make some experiment in real normal weather, and it can achieve a general performance since the SJDL is proposed for auxiliary learning. By the way, we can demonstrate that our method is general for normal images by SJDL's rank 10 of Fig. 5.
